# Encoding: utf-8
# Version: 1.0.0
from collections import defaultdict

import numpy as np
import pandas as pd
from numpy import mean


sigma_map = {  # Customized thresholds based on the three-sigma rule: 68.27%, 95.45%, and 99.73% from 1 sigma to 3 sigma.
    1: 1,
    2: 0.90,
    3: 0.75,
    -1: 0
}


class TemporalStateModel:
    def __init__(self, operation, flow_ts_packets, length_sequence, time_distributions):
        self.operation = operation
        self.flow_ts_packets = flow_ts_packets
        if flow_ts_packets:  # generated by flow_ts_packets
            self.length_sequence = self.extract_length_sequence()
            self.time_distributions = self.extract_time_distributions()
        else:  # generated by parameters
            self.length_sequence = length_sequence
            self.time_distributions = time_distributions
        self.current_index = 0  # Current position in the sequence to check against
        self.matched_packets = []
        self.matched_probabilities = []


    def extract_length_sequence(self):
        """
        Extract the length sequence from the aggregated ts_packets.

        Returns
        -------
        length_sequence: list, the length sequence
        """
        length_sequence = []
        for flow_key, flow in self.flow_ts_packets.items():
            for i in range(len(flow)):
                length_sequence.append(flow[i][2])
            break
        return length_sequence


    def extract_time_distributions(self):
        """
        Extract the mean and standard deviation of each time distributions

        Returns
        -------
        time_distributions: dictionary, the mean and standard deviation of each time distributions
        """
        time_dict = defaultdict(list)
        for key, flow in self.flow_ts_packets.items():
            for i in range(len(flow)):
                time_dict[i].append(float(flow[i][0]))  # flow[i][1]: time

        time_distributions = {}
        for key, times in time_dict.items():
            mean = np.mean(times)
            std_dev = np.std(times)
            time_distributions[key] = (mean, std_dev)
        return time_distributions


    def check_time_range(self, my_time, n_sigma):
        """
        Chech whether my_time is within the time range.

        Parameters
        ----------
        my_time: the relative time of the ts_packet
        n_sigma: n sigma rule

        Returns
        -------
        True if my_time is within the time range, False otherwise
        """
        lower_bound = self.time_distributions[self.current_index][0] - self.time_distributions[self.current_index][1] * n_sigma
        upper_bound = self.time_distributions[self.current_index][0] + self.time_distributions[self.current_index][1] * n_sigma
        if lower_bound <= my_time <= upper_bound:
            return True
        else:
            return False


    def match(self, ts_packet, n_sigma):
        """
        Match the ts_packet with the current TSM by the directional length and the relative time

        Parameters
        ----------
        ts_packet
        n_sigma: n sigma rule

        Returns
        -------
        True: match, False: otherwise
        """
        if ts_packet[2] == self.length_sequence[self.current_index]:  # if the packet length is unmatched, continue to the next packet
            if self.check_time_range(ts_packet[0], n_sigma):  # if the relative time is out of the range, abandon all previous matched packets and reset the TSM
                self.current_index += 1
                self.matched_packets.append(ts_packet)
                return True
            else:
                # print("Unmatched Time")
                self.reset()
                return False
        else:
            return False


    def check(self, flow_ts_packets, n_sigma):
        """
        Check whether a sequence of ts_packets match with the TSM

        Parameters
        ----------
        flow_ts_packets: a sequence of ts_packets
        n_sigma: n sigma rule

        Returns
        -------
        True: match, False: otherwise
        """
        for pkt in flow_ts_packets:
            if self.match(pkt, n_sigma):
                if self.is_totally_matched():  # the size of flow_ts_packets may be larger than that of this moodel
                    return True
                continue
        return False


    def check_time_range_auto(self, my_time):
        """
        Chech whether my_time is within the time range.

        Parameters
        ----------
        my_time: the relative time of the ts_packet

        Returns
        -------
        sigma_map[my_n_sigma]: a customized match probability
        """
        my_n_sigma = -1
        for n_sigma in range(1, 4):
            lower_bound = self.time_distributions[self.current_index][0] - self.time_distributions[self.current_index][1] * n_sigma
            upper_bound = self.time_distributions[self.current_index][0] + self.time_distributions[self.current_index][1] * n_sigma
            if lower_bound <= my_time <= upper_bound:
                my_n_sigma = n_sigma
                break
        original_pro = sigma_map[my_n_sigma]
        modified_pro = original_pro * (1 - self.time_distributions[self.current_index][1] * n_sigma)
        # return original_pro
        return modified_pro


    def match_auto(self, ts_packet):
        """
        Match the ts_packet with the current TSM by the directional length and the relative time

        Parameters
        ----------
        ts_packet

        Returns
        -------
        my_score: match probability
        """
        if ts_packet[2] == self.length_sequence[self.current_index]:  # if the packet length is unmatched, continue to the next packet
            my_score = self.check_time_range_auto(ts_packet[0])
            # my_score = 1  # Disable the time attribute
            if my_score > 0:
                self.current_index += 1
                self.matched_packets.append(ts_packet)
                self.matched_probabilities.append(my_score)
                return my_score
            else:  # if the relative time is out of the range, abandon all previous matched packets and reset the TSM
                # print("Unmatched Time")
                self.reset()
                return my_score
        else:
            return 0


    def check_auto(self, flow_ts_packets):
        """
        Check whether a sequence of ts_packets match with the TSM

        Parameters
        ----------
        flow_ts_packets: a sequence of ts_packets

        Returns
        -------
        match probability
        """
        for pkt in flow_ts_packets:
            if self.match_auto(pkt) > 0:
                if self.is_totally_matched():  # the size of flow_ts_packets may be larger than that of this model
                    return self.calculate_match_probability()  # maybe use the average value of scores
                continue
        return 0


    def calculate_match_probability(self):
        """
        Calculate the match probability based on the sequence of match scores

        Returns
        -------
        match probability
        """
        # Calculate Q1(25) or Q3(75)
        # return np.percentile(self.matched_probabilities, 75)
        # Calculate mean
        return mean(self.matched_probabilities)
        # Calculate min
        # return min(self.matched_probabilities)


    def is_totally_matched(self):
        if self.current_index == len(self.length_sequence):
            return True


    def reset(self):
        """
        Reset the state of the temporal state model

        Returns
        -------
        None
        """
        self.current_index = 0  # Current position in the sequence to check against
        self.matched_packets = []
        self.matched_probabilities = []


    def to_string(self):
        tuples = []
        for i in range(len(self.time_distributions)):
            tuples.append((self.length_sequence[i], f"{self.time_distributions[i][0]:.6f}", f"{self.time_distributions[i][1]:.6f}"))
        # Convert tuples to a string
        result_string = ", ".join(f"({a}::{b}::{c})" for a, b, c in tuples)
        return result_string


    @classmethod
    def construct_flows(cls, operation, flow_ts_packets):
        """
        Construct a TSM object from flow_ts_packets.

        Parameters
        ----------
        operation: operation string
        flow_ts_packets: a flow of ts_packets

        Returns
        -------
        TSM object
        """
        return cls(operation, flow_ts_packets, length_sequence = None, time_distributions = None)


    @classmethod
    def construct_str_tsm(cls, operation, str_tsm):
        """
        Construct a TSM object from a TSM string.

        Parameters
        ----------
        operation: operation string
        str_tsm: TSM string

        Returns
        -------
        TSM object
        """
        flow_ts_packets = None

        str_states = str_tsm.split(", ")
        length_sequence = []
        time_distributions = {}
        for i in range(len(str_states)):
            elements = str_states[i].strip("()").split("::")
            length_sequence.append(elements[0])
            time_distributions[i] = (float(elements[1]), float(elements[2]))

        return cls(operation, flow_ts_packets, length_sequence, time_distributions)
